# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-08-05 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20240802_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ca_approve',
            field=models.BooleanField(default=False),
        ),
    ]
