# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-08-30 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20240830_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='userid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specialist',
            name='specialist',
            field=models.CharField(max_length=100),
        ),
    ]
