# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-08-30 16:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20240830_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist',
            name='userid',
        ),
        migrations.AddField(
            model_name='specialist',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
