# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-08-30 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20240830_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist',
            name='user',
        ),
        migrations.AddField(
            model_name='specialist',
            name='userid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
